// ============================================================
// Ask Key — corpus generator (build-time, re-runnable)
// ============================================================
// Extracts the article library (CONTENT + ARTICLE_BODIES) from
// ../../../index.html and emits corpus.ts, a plain-text corpus the
// ask-claude Edge Function embeds and caches (cache_control) as its
// grounding source.
//
// RE-RUN THIS whenever the Learn articles change materially, then
// re-deploy the function (the corpus is a build-time snapshot):
//   node supabase/functions/ask-claude/build-corpus.mjs
//
// Notes:
//  - HTML is stripped to plain text. Layout-only <div> number cards
//    collapse to their text, which is fine for grounding.
//  - Em/en dashes are intentionally LEFT INTACT here: the dash rule
//    governs the assistant's OUTPUT (system prompt + client sanitiser),
//    not the source it reads.
//  - No secrets, no user data: this touches only static article copy.
// ============================================================
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const INDEX = join(__dirname, "..", "..", "..", "index.html");
const OUT = join(__dirname, "corpus.ts");

const html = readFileSync(INDEX, "utf8");

// ── slice out the two literals by their stable markers ──────────
function slice(src, startMarker, endMarker, endInclusive = false) {
  const i = src.indexOf(startMarker);
  if (i < 0) throw new Error(`marker not found: ${startMarker}`);
  const j = src.indexOf(endMarker, i);
  if (j < 0) throw new Error(`end marker not found: ${endMarker}`);
  return src.slice(i, endInclusive ? j + endMarker.length : j);
}

const contentSrc = slice(html, "const CONTENT = [", "\n];", false) + "\n]";
const bodiesSrc = slice(html, "const ARTICLE_BODIES = {", "}; // end ARTICLE_BODIES", false) + "}";

// ── evaluate with our own _art so bodies come back as parts, not HTML ──
const _art = (body, tips, bw, cta) => ({ __art: true, body, tips, bw });
const evalLiteral = (assignment, name) =>
  new Function("_art", `${assignment}; return ${name};`)(_art);

const CONTENT = evalLiteral(contentSrc, "CONTENT");
const ARTICLE_BODIES = evalLiteral(bodiesSrc, "ARTICLE_BODIES");

// ── HTML -> plain text ──────────────────────────────────────────
function stripTags(s) {
  return String(s)
    .replace(/<li[^>]*>/gi, "\n- ")
    .replace(/<\/(p|div|h\d|ul|ol)>/gi, "\n")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&#39;|&rsquo;|&lsquo;/g, "'")
    .replace(/&quot;|&ldquo;|&rdquo;/g, '"')
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/[ \t]{2,}/g, " ")
    .trim();
}

// ── assemble the corpus text ────────────────────────────────────
const parts = ["# Key Wellness Article Library", ""];
for (const c of CONTENT) {
  parts.push(`## ${c.title}  (${c.cat})`);
  if (c.desc) parts.push(stripTags(c.desc));
  const b = ARTICLE_BODIES[c.title];
  if (b && b.__art) {
    parts.push("");
    parts.push(stripTags(b.body));
    const tips = stripTags(b.tips);
    if (tips) parts.push("", "Key takeaways:", tips);
    const bw = stripTags(b.bw);
    if (bw) parts.push("", `In Botswana: ${bw}`);
  }
  parts.push("", "---", "");
}
const corpus = parts.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";

// ── emit corpus.ts ──────────────────────────────────────────────
const banner =
  "// AUTO-GENERATED by build-corpus.mjs from index.html — do not edit by hand.\n" +
  "// Re-run:  node supabase/functions/ask-claude/build-corpus.mjs\n" +
  `// Articles: ${CONTENT.length}. Approx chars: ${corpus.length}.\n\n`;
const body = "export const ARTICLE_CORPUS = " + JSON.stringify(corpus) + ";\n";
writeFileSync(OUT, banner + body, "utf8");

const approxTokens = Math.round(corpus.length / 4);
console.log(`corpus.ts written: ${CONTENT.length} articles, ${corpus.length} chars (~${approxTokens} tokens).`);
const withBodies = CONTENT.filter((c) => ARTICLE_BODIES[c.title]).length;
console.log(`articles with full bodies: ${withBodies}/${CONTENT.length}.`);
